version: "3"
services:
  db:
    image: javajudd/nuez-db:1.0
    ports:
      - "3306:3306"
    environment:
       MYSQL_USER: ${DB_USER}
       MYSQL_PASSWORD: ${DB_PASSWORD}
       MYSQL_DATABASE: ${DB_DB}
       MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
  web:
    image: javajudd/nuez:1.0
    ports:
      - "80:8080"
    environment:
       DB_USER: ${DB_USER}
       DB_PASSWORD: ${DB_PASSWORD}
       DB_DB: ${DB_DB}
       DB_SERVER: db
       DB_PORT: 3306